jdk: oraclejdk8
language: android
android:
  components:
  - build-tools-28.0.3
  - android-28
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew exportVersion --daemon"
- "./gradlew :app:assembleRelease --daemon --parallel"
before_install:
- yes | sdkmanager "platforms;android-28"
- wget https://github.com/anggrayudi/android-hidden-api/files/2709802/android.zip
- rm /usr/local/android-sdk/platforms/android-28/android.jar
- mv ./android.zip /usr/local/android-sdk/platforms/android-28/android.jar
- chmod a+x gradlew
- openssl aes-256-cbc -K $encrypted_87dd0b6bf67f_key -iv $encrypted_87dd0b6bf67f_iv -in secrets.tar.enc -out ./secrets.tar -d
- tar xvf secrets.tar
before_deploy:
- export VERSION=$(cat version.txt)
- export VERSION_CODE=$(cat version_code.txt)
- git tag $VERSION_CODE
- mv "app/build/outputs/apk/release/app-release.apk" "app/build/outputs/apk/release/app-${VERSION}.apk"
- mv "app/build/outputs/mapping/release/mapping.txt" "app/build/outputs/mapping/release/mapping-${VERSION}.txt"
deploy:
  name: ${VERSION}
  body: Snapshot version automatically generated by Travis CI. Please be cautious to experience due to potential bugs.
  prerelease: true
  provider: releases
  skip_cleanup: true
  api_key:
    secure: qPkG/FD5FdpnVBje4/RVCe0xK+nVVvItlhzeGYTX9IKzDQN8cKpDuYSx2Y0eyFlH1umTz2vwGkLhX2dFkoXik20woOe4oAyAetb4y9farsLldnZ+xE2fcyePXXkwHgSOv3ktzRAZ56kk124IKHQpv/JUzW1M7XI6P0YgvJ7QZgRDR8lHk1OdozZtjdFDS9PF0p4AJhEeLjAalGI8KDxhPn0DVu2OUP4vo+eldoOeK7R2YJuB+U4FaUAMe6bLtW+D7yolr5OItsatnrE+cM9IzR4MvqQJ7VoD3zocSAmMzIjiP2AoA/9tcTvWAwTXPvzpwA325gL6sgQSlVJ876tHbjwNe/+90Az28s3yS1iBDdYVvq36gyLgpAGSajYDVwfsHUT1aZ7HBngg7vaOwxC6eod/KONziUeKUyL7MrLT1eEz2i8F89/KuZF2boHS/NNn2TRUsLeNzhLSs8zlNtZvWeGLyA/DyCZZ8bOhOPftd6ulBIqq8ptmKGoUc44eDrm8/ctj7dChljCgXrv70DwWGWmj07jos0FmSc7OsSp83FQ2gvtd+KiotpTx3/j9FWbZbap3vhRxO4FshSDHSf9xcu9MONQ/1asQzwfwMpdNvBrSI8UQ6JJ8/3WNp4NGPBgvqkoJvGfymDJkUk7GP7v1eTf/ACr4o/6lcviEI0Ekz3A=
  file:
    - app/build/outputs/apk/release/app-${VERSION}.apk
    - app/build/outputs/mapping/release/mapping-${VERSION}.txt
  on:
    repo: Trumeet/SysUIController